### Получение списка всех сотрудников
GET http://localhost:8080/employees

### Получение суммы зарплат всех сотрудников
GET http://localhost:8080/employees/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение сотрудников с з/п больше средней
GET http://localhost:8080/employees/high-salary


// По департаментам:

### Возвращает всех сотрудников, сгруппированых по отделам
GET http://localhost:8080/department/employees

### Возвращает список сотрудников заданного отдела
GET http://localhost:8080/department/dep=2/employees

### Возвращает сумму зарплат по отделу
GET http://localhost:8080/department/dep=2/salary/sum

### Возвращает максимальную зарплату по отделу
GET http://localhost:8080/department/{}/salary/max

### Возвращает минимальную зарплату по отделу
GET http://localhost:8080/department/{}/salary/min