###Получение списка сотрудников
GET http://localhost:8080/employees

###Добавление сотрудника 1
POST http://localhost:8080/employee
Content-Type: application/json

{
  "name": "john",
  "surname": "watson",
  "department": 1,
  "salary": 1000
}

###Добавление сотрудника 2
POST http://localhost:8080/employee
Content-Type: application/json

{
  "name": "Jane",
  "surname": "Austen",
  "department": 4,
  "salary": 2000
}

###Добавление сотрудника 3
POST http://localhost:8080/employee
Content-Type: application/json

{
  "name": null,
  "surname": "",
  "department": 4,
  "salary": 2000
}

### Получение суммы зарплат сотрудников
GET http://localhost:8080/employees/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/high-salary